#!/usr/bin/env python3
"""
tests/gen_env_doc.py  v1.0
v1.0  2026-10-04  OTV4TEST r250 (DOC.31 item 4, audit D8) — docs/ENV.md IS GENERATED FROM THE CODE: every OT_* environment variable
      the tree reads, its default(s) as written at each read, and every file:line that reads it. ~200 variables lived only in the
      code, and the docs named a handful. The operator, 2026-10-04: "finish what you can" (the weekend's leftovers).

  HOW: an AST walk of every .py outside venv/ and .git/ - os.environ.get("OT_X"[, default]), os.getenv("OT_X"[, default]),
  os.environ["OT_X"], and "OT_X" in os.environ. A default that is not a literal is shown as `<expr>`. A variable read ONLY under
  tests/ or tools/ is listed in its own section (it does not configure the bot). Generated text is deterministic (sorted).
  The default is AS WRITTEN AT THE READ - config.py may still transform it (e.g. == "1"); the file:line is the answer.

Run:  python3 tests/gen_env_doc.py            (write docs/ENV.md)
      python3 tests/gen_env_doc.py --check    (exit 1 and name the drift if docs/ENV.md differs from the code)
"""
import ast
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "ENV.md")
SKIP = {"venv", ".git", "__pycache__", "node_modules"}


def _lit(node):
    if node is None:
        return "(none)"
    if isinstance(node, ast.Constant):
        return repr(node.value)
    return "<expr>"


def _is_environ(node):
    # os.environ  (Attribute(value=Name('os'), attr='environ'))
    return (isinstance(node, ast.Attribute) and node.attr == "environ"
            and isinstance(node.value, ast.Name) and node.value.id == "os")


def scan():
    reads = defaultdict(list)          # var -> [(relpath, line, default)]
    for dp, dirs, files in os.walk(ROOT):
        dirs[:] = sorted(d for d in dirs if d not in SKIP and not d.startswith("wt-"))
        for f in sorted(files):
            if not f.endswith(".py"):
                continue
            path = os.path.join(dp, f)
            rel = os.path.relpath(path, ROOT)
            try:
                tree = ast.parse(open(path, encoding="utf-8").read())
            except (SyntaxError, UnicodeDecodeError):
                continue
            for n in ast.walk(tree):
                var, dflt = None, None
                if isinstance(n, ast.Call) and n.args and isinstance(n.args[0], ast.Constant) \
                        and isinstance(n.args[0].value, str) and n.args[0].value.startswith("OT_"):
                    fn = n.func
                    if (isinstance(fn, ast.Attribute) and fn.attr == "get" and _is_environ(fn.value)) or \
                            (isinstance(fn, ast.Attribute) and fn.attr == "getenv"
                             and isinstance(fn.value, ast.Name) and fn.value.id == "os"):
                        var = n.args[0].value
                        dflt = _lit(n.args[1]) if len(n.args) > 1 else "(none)"
                elif isinstance(n, ast.Subscript) and _is_environ(n.value):
                    k = n.slice
                    if isinstance(k, ast.Constant) and isinstance(k.value, str) and k.value.startswith("OT_"):
                        var, dflt = k.value, "(required)" if isinstance(n.ctx, ast.Load) else "(set here)"
                elif isinstance(n, ast.Compare) and len(n.ops) == 1 and isinstance(n.ops[0], (ast.In, ast.NotIn)) \
                        and isinstance(n.left, ast.Constant) and isinstance(n.left.value, str) \
                        and n.left.value.startswith("OT_") and _is_environ(n.comparators[0]):
                    var, dflt = n.left.value, "(presence)"
                if var:
                    reads[var].append((rel, n.lineno, dflt))
    return reads


def render(reads):
    def bot(locs):
        return any(not (r.startswith("tests" + os.sep) or r.startswith("tools" + os.sep)) for r, _l, _d in locs)
    runtime = sorted(v for v, locs in reads.items() if bot(locs))
    toolonly = sorted(v for v, locs in reads.items() if not bot(locs))
    out = ["<!-- GENERATED by tests/gen_env_doc.py - do not edit by hand; regenerate. -->",
           "# ENV.md — every OT_* variable the code reads",
           "",
           f"**{len(reads)} variables: {len(runtime)} read by the bot / deploy code, {len(toolonly)} only by tests/ or tools/.**",
           "The default is AS WRITTEN AT THE READ (config.py may still transform it, e.g. `== \"1\"`); the file:line is the answer.",
           "Unit `Environment=` lines set these; NEVER print a unit's Environment block to read them (WORKING_AGREEMENT §18a).",
           ""]
    for title, names in (("Read by the bot and deploy code", runtime), ("Read only by tests/ and tools/", toolonly)):
        out += [f"## {title}", "", "| variable | default(s) as written | read at |", "|---|---|---|"]
        for v in names:
            locs = sorted(reads[v])
            dfl = ", ".join(sorted({d.replace("|", "\\|") for _r, _l, d in locs}))
            where = ", ".join(f"`{r}:{l}`" for r, l, _d in locs)
            out.append(f"| `{v}` | {dfl} | {where} |")
        out.append("")
    return "\n".join(out)


def main(argv):
    text = render(scan())
    if "--check" in argv:
        try:
            cur = open(OUT, encoding="utf-8").read()
        except OSError:
            print("  DRIFT: docs/ENV.md is missing - run python3 tests/gen_env_doc.py")
            return 1
        if cur != text:
            a, b = set(cur.splitlines()), set(text.splitlines())
            print("  DRIFT: docs/ENV.md does not match the code")
            for l in sorted(b - a)[:8]:
                print("    + " + l[:150])
            for l in sorted(a - b)[:8]:
                print("    - " + l[:150])
            return 1
        print("  env doc is current")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"  wrote docs/ENV.md: {text.count(chr(10)+'| `OT_')} variables")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
